CREATE SEQUENCE destination_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 CREATE SEQUENCE item_seq
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

CREATE TABLE "DESTINATION"(
    ID NUMBER PRIMARY KEY, 
    NAME VARCHAR2(200 CHAR) not null
);

DROP TABLE "DESTINATION";

COMMENT ON TABLE "DESTINATION"  IS 'All destinations';

COMMENT ON COLUMN "DESTINATION".ID IS 'Primary key';
COMMENT ON COLUMN "DESTINATION".NAME IS 'Name of destination';


CREATE TABLE "ITEM"(
    ID NUMBER PRIMARY KEY, 
    NAME VARCHAR2(200 CHAR) not null,
    DESTINATION_ID NUMBER not null
);

COMMENT ON TABLE "ITEM"  IS 'All items';

COMMENT ON COLUMN "ITEM".ID IS 'Primary key';
COMMENT ON COLUMN "ITEM".NAME IS 'Name of item';
COMMENT ON COLUMN "ITEM".DESTINATION_ID IS 'Foreign key';
COMMENT ON COLUMN "ITEM".DONE IS 'Packed Boolean';

ALTER TABLE "ITEM" 
    ADD CONSTRAINT "ITEM_DESTINATION" 
    FOREIGN KEY (DESTINATION_ID) 
    REFERENCES "DESTINATION"(ID) 
    ENABLE;
    
 ALTER TABLE "ITEM" 
    ADD DONE NUMBER not null;
    
    